## 访问网站 (c++ 爬虫)

Q1：使用 ```asio::read()``` 时，若使用签名 ```std::size_t read(SyncReadStream& s, asio::basic_streambuf<Allocator>& b)``` 则在一开始读取 socket 时就会抛出 "read: End of file" 的异常。使用3个参数及以上的签名，比如 ```std::size_t read(SyncReadStream& s, asio::basic_streambuf<Allocator>& b, asio::error_code& ec)``` 或者 ```std::size_t read(SyncReadStream& s, asio::basic_streambuf<Allocator>& b, CompletionCondition completion_condition)```才没有抛出该异常。不过，不带 ```asio::error_code``` 参数的签名总是在最后会抛出 "read: End of file" 的异常。

A1：首先明确一个点：**只有在源缓冲区中已经没有数据的时候再进行读取操作才会产生EOF异常**。也就是说，假如源缓冲区中仍然存在数据，虽然目标缓冲区的大小远远超过剩余数据的大小，但是仍然只能读取这部分数据，而且并不会产生EOF异常。之后，分2种方面讨论对上述问题进行讨论。另外，插句题外话：```read()``` 调用 ```socket.read_some()``` 和 ```completion_condition(const Error& err, std::size_t bytes_transferred)``` 。
1. 具有 ```asio::error_code``` 参数的签名，这种时候 read 在遇到异常的时候，会设置该变量，并返回给 read 的调用方，由调用方负责处理该异常。
2. 关于 ```completion_condition``` 的讨论
    2.1 ```completion_condition``` 为 ```asio::transfer_all()``` 时，会读取至发生EOF异常再结束，此时若签名中不包含 ```asio::error_code``` 参数，就会抛出EOF异常，直到有 catch 捕获异常为止
    2.2 ```completion_condition``` 为 ```asio::transfer_at_least(size_t num)``` 时，每一次读取只要求数据量 > num 即可。且最后一次读取的时候，读取的数据量为0,并且抛出EOF异常。倘若 read 的调用者以数据量为循环条件，比如 
    ```while(read(SyncReadStream& s, asio::basic_streambuf<Allocator>& b, CompletionCondition completion_condition, asio::error_code& ec))```

    ，那么最后一次跳出循环的原因并不是抛出了EOF异常，而是读取的数据量为0。

Q2：访问某些网站时只能使用 https ，不能使用 http 。

A2：使用 https 访问网站时，需要用到 ssl 层，可以理解为在 tcp 层的基础上再建立一层 ssl 层的连接。这里使用 asio 封装的 api，具体实现由 openssl 提供。使用 SSL 进行 https 访问时，主要步骤为：
1. 创建 tcp socket
2. 建立 ssl 连接
    1. 建立 ssl 会话环境/上下文
    2. 建立 ssl 流，包裹 tcp socket（相当于底层为该 tcp socket）
    3. 使用 ssl 流与服务端建立连接
        1. **连接 connect**。调用 ```asio::connect(sslStream.lowest_layer(), endpoints)``` 进行 tcp 连接
        2. **握手 handshake**。调用 ```sslStream.handshake(asio::ssl::stream_base::client)``` 进行 ssl 客户端 handshake
3. 基于 ssl 进行数据传输/socket读写，```asio::ssl::stream``` 里已经包含了 ```write_some()``` 和 ```read_some()``` 方法，因此可以使用 ```asio::write()``` 和 ```asio::read()``` 方法包裹 ssl 的读写

**! 当我们使用 c 风格的网络编程时，可以使用 openssl 提供的 api，但是在最后需要我们手动按顺序执行**
```c
SSL_shutdown() // 关闭 SSL
SSL_free(SSL *) // 释放 SSL
SSL_CTX_free(SSL_CTX *) // 释放 SSL 上下文
close(fd *) // 关闭 tcp socket
```

Q3：客户端写好各种异步操作之后，发现并没有异步调用。后来只开始了一层异步调用，并返回错误代码 125, 错误信息 *Operation aborted.*

A3：
刚开始是没有调用 ```io_context.run()``` 方法进入事件循环，之后报错误码是另一个原因。查看类 ```Visitor``` 的相关代码段
```c++
void resolve() {
    tcp::resolver resolver(ic);
    tcp::resolver::query q(host, service);
    resolver.async_resolve(q, boost::bind(
        &Visitor::handleResolve, this, boost::placeholders::_1, boost::placeholders::_2)
    );
}

void handleResolve(const asio::error_code &ec, tcp::resolver::results_type results) {
    if (!ec) {
        endpoints = results;
        connect();
    } else {
        cerr << __LINE__ << ": " << ec.value() << ", " << ec.message() << endl;
    }
}
```
* **原因** 可以看到，函数内部新建了局部对象 ```resolver```，也正是该对象指定了异步调用。然而，在离开该函数之后，该局部变量失效，生命周期结束，因此在外部的 ```io_context``` 在事件到来时无法确认触发该事件的对象身份，就会设置错误码，在异步调用的方法中，判断存在错误即结束异步调用。
* **解决方案** 将 ```resolver``` 提取为类成员变量，可以延长其生命周期。

Q4：在实现支持重定向访问直至得到成功响应的访问器时，遇到一个问题。当前一个请求是 https 方法，收到的响应是重定向到另一个 https 地址后，此时再进行 https 请求，就会发生 ```asio::ssl::stream``` 在发送数据后，读取数据时会没有数据，直接读取到 eof 的情况。

A4：**这里暂时没有找到相关的文字资料，因此下面的文字不一定正确。**通过大量的尝试之后，我们发现只要在下一次请求之前重新创建 ```asio::ssl::stream``` 对象，就可以避免直接读取到 eof 这种情况。这说明 ```asio::ssl::stream``` 的使用是有一定的限制的。**初步估计** ```asio::ssl::stream``` 如同 socket 套接字一样，存在可复用性的问题，因此每次请求前都需要创建一个新的 ```asio::ssl::stream``` 。

Q5：在连接 www.nipic.com 时，发生错误，错误码为 1，错误信息为 *stream truncated*。

A5：